#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

root_dir=$(git rev-parse --git-dir)
root_dir=$(cd $root_dir > /dev/null && cd .. > /dev/null && pwd -P)

cd $root_dir

yarn precommit
