# Copyright 2024 Circle Internet Group, Inc. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Coverage
on:
  pull_request:
    types: [labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_coverage:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'needs_coverage' }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup CI Environment
        uses: ./.github/composite-actions/setup-ci

      - name: Compile contracts
        run: yarn compile

      - name: Run coverage
        run: yarn coverage

      - name: Report coverage to PR
        id: report-coverage
        uses: sidx1024/report-nyc-coverage-github-action@v1.2.7
        with:
          coverage_file: "coverage/coverage-summary.json"
          base_coverage_file: ""
          comment_template_file: ".github/resources/coverage-report-template.md"

      - name: Check coverage
        if: |
          fromJSON(steps.report-coverage.outputs.total_lines_coverage_percent_raw) < 100 ||
          fromJSON(steps.report-coverage.outputs.total_branches_coverage_percent_raw) < 98 ||
          fromJSON(steps.report-coverage.outputs.total_statements_coverage_percent_raw) < 100 ||
          fromJSON(steps.report-coverage.outputs.total_functions_coverage_percent_raw) < 100
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('Test coverage is under the threshold')
