name: Deploy Branch Sync
on:
  push:
    branches:
      - master

env:
  PR_HEAD: ${{ format('{0}:master', github.repository_owner) }}
  PR_BASE: deploy

jobs:
  auto_sync:
    runs-on: circle-small
    steps:
      - name: Check out repository code
        if: ${{ github.repository_owner == 'circlefin' }}
        uses: actions/checkout@v3

      - name: Read secrets from AWS Secrets Manager into environment variables
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          parse-json-secrets: true
          secret-ids: |
            /ops/utilities/github-actions-bot/api-token

      - name: Check if pull request already exists
        id: check-if-pr-exists
        uses: actions/github-script@v7
        with:
          github-token: ${{ env._OPS_UTILITIES_GITHUB_ACTIONS_BOT_API_TOKEN }}
          script: |
            try {
              const response = await github.rest.pulls.list({
                owner: context.repo.owner,
                repo: context.repo.repo,
                head: process.env.PR_HEAD,
                base: process.env.PR_BASE,
                state: "open"
              });
              core.setOutput('has-open-pr', (response.data.length > 0).toString())
            } catch (e) {
              core.error(JSON.stringify(e.response.data));
              core.setFailed(`Error found: ${e.response.data.message}`);
            }

      - name: Create pull request
        uses: actions/github-script@v7
        if: ${{ steps.check-if-pr-exists.outputs.has-open-pr != 'true' }}
        with:
          github-token: ${{ env._OPS_UTILITIES_GITHUB_ACTIONS_BOT_API_TOKEN }}
          script: |
            try {
              const response = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: "[SYNC] Update deploy branch with master",
                head: process.env.PR_HEAD,
                base: process.env.PR_BASE
              });
              core.exportVariable("PR_NUMBER", response.data.number);
            } catch (e) {
              core.error(JSON.stringify(e.response.data));
              core.setFailed(`Error found: ${e.response.data.message}`);
            }

      - name: Request for reviews
        uses: actions/github-script@v7
        if: ${{ steps.check-if-pr-exists.outputs.has-open-pr != 'true' }}
        with:
          github-token: ${{ env._OPS_UTILITIES_GITHUB_ACTIONS_BOT_API_TOKEN }}
          script: |
            try {
              await github.rest.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: process.env.PR_NUMBER,
                team_reviewers: ['engineering-centre-tokens-approvers']
              });
            } catch (e) {
              core.error(JSON.stringify(e.response.data));
              core.setFailed(`Error found: ${e.response.data.message}`);
            }
